---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-frontend-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-frontend
  template:
    metadata:
      labels:
        app: portfolio-frontend
 
    spec:
      containers:
      - name: portfolio-frontend
        image: devarangan/portfolio-frontend
        envFrom:
        - secretRef:
            name: my-secret
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-service
spec:
  selector:
    app: portfolio-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30000
  type: NodePort